### PR TITLE
Temporary fix to shutil.copy same file copy error

### PR DESCRIPTION
**Pull request by kimt33**
In trapdoor_pycodestyle and trapdoor_pylint, pycodestyle.ini and pylinrc
are copied over to qaworkdir respectively. It finds these files
relative to the directory in which these modules/python files are
located. When simulating trapdoors, the trapdoor scripts are copied over
to qaworkdir for some reason, and shutil.copy raises an error saying
that you cannot copy over the same file to itself.
For now, I've added a check to make sure that the files that are copied
from and to are not the same.
But for the long run, these config files need to be dealt with in a more
elegant manner (and i'm not too sure why the trapdoors are copied over
also)

### CODE REVIEW

**Comment by matt-chan** [comment]
I'm not sure if you have a configuration error? The QAWORKDIR shouldn't ever the same as the qatooldir. The tooldir is the original location of the trapdoor scripts in the repo, while the workdir is the one that the trapdoors write to for storing temporary data between commits. 

The trapdoors themselves have to be copied because there's no guarantee that the trapdoor scripts themselves are the same between different commits, so sometimes you can get a problem where the trapdoors don't exist in the ancestor commit, or have a different version. (This isn't as big a problem in the submodule case I think, but HORTON still has QA tools directly in it). It'll get fixed in the next release of HORTON and we can get rid of the QAWORKDIR (I think).

**Comment by kimt33** [comment]
I think this error comes up when you `simulate_trapdoor_pr.py`. In line 291, the script is copied over to the qaworkdir, and since qatooldir is always with respect to the location of the file that is being run, you get a conflict when you execute the copied script (line 304). I don't get this problem when I run this trapdoor explicitly or if I run it through travis (`test_all_twobranches.sh`). It seems to be a problem isolated to simulate_trapdoor_py.py.
Maybe change `copied_script` from line 304 to `script`?

**Comment by kimt33** [comment]
Oh yeah, and I added another commit that fixes the `tab in indent` error in chemtools' travis. I just made trapdoor skip that commit explicitly.

**Comment by kimt33** [comment]
It seems that changing `copied_script` to `script` fixes the issue, but I'm not confident that I understand what the code is doing from that point onwards. Is it possible for that the script changes in qaworkdir (so you don't want to use the one from qatooldir)?

**Comment by kimt33** [comment]
Let me know if you want me to change this from `copied_script` to `script` so I can force change that other commit.

**Pull request closed without merging**
